### ISSUE TITLE
Compilation warnings in PG11 and final error upon CREATE EXTENSION

### ISSUE THREAD

**Issue by GHNewbiee** [pjungwir/inetrange#3] opened 2018-10-22 16:46 UTC
Hi,

I tried to compile the extension for PG11 but the following warnings appeared:
```
In file included from inetrange.c:9:0:
inetrange_canonical.c: In function ‘inetrange_canonical’:
inetrange_canonical.c:11:19: warning: implicit declaration of function ‘PG_GETARG_RANGE’ [-Wimplicit-function-declaration]
   RangeType  *r = PG_GETARG_RANGE(0);
                   ^
inetrange_canonical.c:11:19: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
inetrange_canonical.c:21:14: warning: implicit declaration of function ‘PG_RETURN_RANGE’ [-Wimplicit-function-declaration]
   if (empty) PG_RETURN_RANGE(r);
              ^
inetrange_canonical.c:34:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

Moreover, when I tried to `CREATE  EXTENSION inetrange ...` I got the following error:
```
Query execution failed

Reason:
SQL Error [XX000]: ERROR: could not load library "/usr/lib/postgresql/11/lib/inetrange.so": /usr/lib/postgresql/11/lib/inetrange.so: undefined symbol: PG_GETARG_RANGE
```

Tia

**Comment by pjungwir** [comment] 2018-10-22 16:56
Thank you for the report! I haven't tried building this against pg11 before, but I'll take a look.

**Comment by pjungwir** [comment] 2018-10-22 17:11
Confirmed: I can built it against pg10, but on Ubuntu 16.04 after doing `sudo apt-get install postgresql-11 postgresql-server-dev-11` I get the same errors.

**Comment by pjungwir** [comment] 2018-10-22 17:13
Looks like `PG_GETARG_RANGE` was renamed: https://www.postgresql.org/message-id/11607.1505246855%40sss.pgh.pa.us

**Comment by pjungwir** [comment] 2018-10-22 17:32
Fixed in https://github.com/pjungwir/inetrange/commit/42c467a06d69666dcaf9277acc1ee456f0f884cf and [release 1.0.1](https://pgxn.org/dist/inetrange/).

**Closed as completed by pjungwir** 2018-10-22 17:32 UTC
